package com.baalvion.documentgeneration.dto;

import java.util.Map;
import java.util.UUID;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public class DocumentGenerationRequest {

	@NotNull(message = "Template ID is required")
	private UUID documentTemplateId;

	@NotBlank(message = "Generated by is required")
	private String generatedBy;

	private Map<String, String> placeholders;

	public DocumentGenerationRequest() {
	}

	public DocumentGenerationRequest(UUID documentTemplateId, String generatedBy, Map<String, String> placeholders) {
		this.documentTemplateId = documentTemplateId;
		this.generatedBy = generatedBy;
		this.placeholders = placeholders;
	}

	public UUID getDocumentTemplateId() {
		return documentTemplateId;
	}

	public void setDocumentTemplateId(UUID documentTemplateId) {
		this.documentTemplateId = documentTemplateId;
	}

	public String getGeneratedBy() {
		return generatedBy;
	}

	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	public Map<String, String> getPlaceholders() {
		return placeholders;
	}

	public void setPlaceholders(Map<String, String> placeholders) {
		this.placeholders = placeholders;
	}
}